'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.9164
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  終了します。よろしいですか? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AFX_IDP_ASK_TO_EXIT() As String
            Get
                Return ResourceManager.GetString("AFX_IDP_ASK_TO_EXIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  %1 への変更を保存しますか? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AFX_IDP_ASK_TO_SAVE() As String
            Get
                Return ResourceManager.GetString("AFX_IDP_ASK_TO_SAVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  すべてのファイル (*.*) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AFX_IDS_ALLFILTER() As String
            Get
                Return ResourceManager.GetString("AFX_IDS_ALLFILTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  準備完了 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AFX_IDS_IDLEMESSAGE() As String
            Get
                Return ResourceManager.GetString("AFX_IDS_IDLEMESSAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  %1 - %2 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AFX_IDS_OBJ_TITLE_INPLACE() As String
            Get
                Return ResourceManager.GetString("AFX_IDS_OBJ_TITLE_INPLACE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  1 ページ(&amp;O) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AFX_IDS_ONEPAGE() As String
            Get
                Return ResourceManager.GetString("AFX_IDS_ONEPAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ページ %u\nページ %u-%u\n に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AFX_IDS_PREVIEWPAGEDESC() As String
            Get
                Return ResourceManager.GetString("AFX_IDS_PREVIEWPAGEDESC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ページ %u に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AFX_IDS_PRINTPAGENUM() As String
            Get
                Return ResourceManager.GetString("AFX_IDS_PRINTPAGENUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  2 ページ(&amp;T) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AFX_IDS_TWOPAGE() As String
            Get
                Return ResourceManager.GetString("AFX_IDS_TWOPAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  無題 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property AFX_IDS_UNTITLED() As String
            Get
                Return ResourceManager.GetString("AFX_IDS_UNTITLED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  プログラム情報、バージョン、著作権を表示します。\nバージョン情報\nﾍﾙﾌﾟ\n著作権情報を表示しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_APP_ABOUT() As String
            Get
                Return ResourceManager.GetString("ID_APP_ABOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  アプリケーションを終了し、ドキュメントの保存を指示\n終了\n終了 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_APP_EXIT() As String
            Get
                Return ResourceManager.GetString("ID_APP_EXIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  選択範囲を消去\n消去\n消去\n消去しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_EDIT_CLEAR() As String
            Get
                Return ResourceManager.GetString("ID_EDIT_CLEAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  すべて消去\nすべて消去\n全消\nすべて消去しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_EDIT_CLEAR_ALL() As String
            Get
                Return ResourceManager.GetString("ID_EDIT_CLEAR_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  選択範囲をコピーしてクリップボードに保存\nコピー\nｺﾋﾟｰ\n選択範囲をクリップボードへコピーしました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_EDIT_COPY() As String
            Get
                Return ResourceManager.GetString("ID_EDIT_COPY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  選択範囲を切り取ってクリップボードに保存\n切り取り\n切取\n選択範囲をクリップボードへ移動しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_EDIT_CUT() As String
            Get
                Return ResourceManager.GetString("ID_EDIT_CUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  指定した文字列の検索\n検索\n検索\n検索文字列を指定してください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_EDIT_FIND() As String
            Get
                Return ResourceManager.GetString("ID_EDIT_FIND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  クリップボードの内容を貼り付け\n貼り付け\n貼付\nクリップボードから貼り付けました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_EDIT_PASTE() As String
            Get
                Return ResourceManager.GetString("ID_EDIT_PASTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  取り消した操作をやり直す\nやり直す\n直す\n変更を取り消しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_EDIT_REDO() As String
            Get
                Return ResourceManager.GetString("ID_EDIT_REDO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  直前に行った動作を繰り返す\n繰り返し\n繰返\n次を検索しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_EDIT_REPEAT() As String
            Get
                Return ResourceManager.GetString("ID_EDIT_REPEAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  指定した文字列を他の文字列で置換\n置換\n置換\n置換文字列を指定してください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_EDIT_REPLACE() As String
            Get
                Return ResourceManager.GetString("ID_EDIT_REPLACE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイル内のすべてを選択\nすべて選択\n全選\nすべて選択しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_EDIT_SELECT_ALL() As String
            Get
                Return ResourceManager.GetString("ID_EDIT_SELECT_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  直前に行った動作を元に戻す\n元に戻す\n戻す\n元に戻しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_EDIT_UNDO() As String
            Get
                Return ResourceManager.GetString("ID_EDIT_UNDO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  作業中のドキュメントを閉じる\n閉じる\n閉じ\nドキュメントを閉じました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_FILE_CLOSE() As String
            Get
                Return ResourceManager.GetString("ID_FILE_CLOSE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  新しいドキュメントを作成\n新規作成\n新規\n新規作成しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_FILE_NEW() As String
            Get
                Return ResourceManager.GetString("ID_FILE_NEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  既存のドキュメントを開く\n開く\n開く\nドキュメントを開きました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_FILE_OPEN() As String
            Get
                Return ResourceManager.GetString("ID_FILE_OPEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  印刷オプションの変更\nページ レイアウトの設定\n頁設\nページ レイアウトを設定しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_FILE_PAGE_SETUP() As String
            Get
                Return ResourceManager.GetString("ID_FILE_PAGE_SETUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  作業中のドキュメントを印刷\n印刷\n印刷\n印刷しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_FILE_PRINT() As String
            Get
                Return ResourceManager.GetString("ID_FILE_PRINT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  作業中のドキュメントを現在のオプションで印刷\nクイック印刷\n印刷\n印刷しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_FILE_PRINT_DIRECT() As String
            Get
                Return ResourceManager.GetString("ID_FILE_PRINT_DIRECT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  印刷イメージを表示\n印刷プレビュー\nプレ\n印刷プレビューしました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_FILE_PRINT_PREVIEW() As String
            Get
                Return ResourceManager.GetString("ID_FILE_PRINT_PREVIEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  プリンターおよび印刷オプションの変更\n印刷設定\n設定\n印刷設定しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_FILE_PRINT_SETUP() As String
            Get
                Return ResourceManager.GetString("ID_FILE_PRINT_SETUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  作業中のドキュメントを上書きして保存\n保存\n保存\nドキュメントを保存しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_FILE_SAVE() As String
            Get
                Return ResourceManager.GetString("ID_FILE_SAVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  作業中のドキュメントを新しい名前で保存\n名前をつけて保存\n名付 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_FILE_SAVE_AS() As String
            Get
                Return ResourceManager.GetString("ID_FILE_SAVE_AS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  CAP に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_INDICATOR_CAPS() As String
            Get
                Return ResourceManager.GetString("ID_INDICATOR_CAPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  列:{0,5} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_INDICATOR_COL() As String
            Get
                Return ResourceManager.GetString("ID_INDICATOR_COL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  yyyy/MM/dd に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_INDICATOR_DATE() As String
            Get
                Return ResourceManager.GetString("ID_INDICATOR_DATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  編集 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_INDICATOR_MODIFY() As String
            Get
                Return ResourceManager.GetString("ID_INDICATOR_MODIFY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  NUM に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_INDICATOR_NUM() As String
            Get
                Return ResourceManager.GetString("ID_INDICATOR_NUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  行:{0,5} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_INDICATOR_ROW() As String
            Get
                Return ResourceManager.GetString("ID_INDICATOR_ROW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SCRL に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_INDICATOR_SCRL() As String
            Get
                Return ResourceManager.GetString("ID_INDICATOR_SCRL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  HH mm\nHH:mm に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_INDICATOR_TIME() As String
            Get
                Return ResourceManager.GetString("ID_INDICATOR_TIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  印刷プレビューを閉じる\n閉じる\n閉じる(&amp;C) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_PREVIEW_CLOSE() As String
            Get
                Return ResourceManager.GetString("ID_PREVIEW_CLOSE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  次のページ\n次のページ\n次へ(&amp;N) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_PREVIEW_NEXT() As String
            Get
                Return ResourceManager.GetString("ID_PREVIEW_NEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  1 ページ表示/2 ページ表示の切り替え\n切り替え\n2ページ(&amp;T) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_PREVIEW_ONEPAGE() As String
            Get
                Return ResourceManager.GetString("ID_PREVIEW_ONEPAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  前のページ\n前のページ\n前へ(&amp;N) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_PREVIEW_PREV() As String
            Get
                Return ResourceManager.GetString("ID_PREVIEW_PREV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  文書の印刷\n印刷\n印刷(&amp;P) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_PREVIEW_PRINT() As String
            Get
                Return ResourceManager.GetString("ID_PREVIEW_PRINT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  設定\n設定\n設定(&amp;T) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_PREVIEW_SETUP() As String
            Get
                Return ResourceManager.GetString("ID_PREVIEW_SETUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  拡大\n拡大\n拡大(&amp;I) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_PREVIEW_ZOOMIN() As String
            Get
                Return ResourceManager.GetString("ID_PREVIEW_ZOOMIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  縮小\n縮小\n縮小(&amp;R) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_PREVIEW_ZOOMOUT() As String
            Get
                Return ResourceManager.GetString("ID_PREVIEW_ZOOMOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ウィンドウ内の各オブジェクトの詳細情報を表示します。\n詳細\n詳細\n詳細表示へ変更しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_VIEW_DETAILS() As String
            Get
                Return ResourceManager.GetString("ID_VIEW_DETAILS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  オブジェクトを大きいアイコンで表示します。\n大きいアイコン\n大\n大きいアイコン表示へ変更しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_VIEW_LARGEICON() As String
            Get
                Return ResourceManager.GetString("ID_VIEW_LARGEICON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  オブジェクトを一覧表示します。\n一覧\n一覧\n一覧表示へ変更しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_VIEW_LIST() As String
            Get
                Return ResourceManager.GetString("ID_VIEW_LIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  オブジェクトを小さいアイコンで表示します。\n小さいアイコン\n小\n小さいアイコン表示へ変更しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_VIEW_SMALLICON() As String
            Get
                Return ResourceManager.GetString("ID_VIEW_SMALLICON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ステータス バーの表示/非表示\nステータス バーの表示切り替え\nステータス バーの表示を変更しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_VIEW_STATUS_BAR() As String
            Get
                Return ResourceManager.GetString("ID_VIEW_STATUS_BAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ツール バーの表示/非表示\nステータス バーの表示切り替え\nツール バーの表示を変更しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ID_VIEW_TOOLBAR() As String
            Get
                Return ResourceManager.GetString("ID_VIEW_TOOLBAR", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_APP_ABOUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_APP_ABOUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_APP_EXIT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_APP_EXIT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_EDIT_COPY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_EDIT_COPY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_EDIT_CUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_EDIT_CUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_EDIT_PASTE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_EDIT_PASTE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_FILE_NEW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_FILE_NEW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_FILE_OPEN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_FILE_OPEN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_FILE_PRINT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_FILE_PRINT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_FILE_SAVE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_FILE_SAVE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_PREVIEW_CLOSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_PREVIEW_CLOSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_PREVIEW_NEXT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_PREVIEW_NEXT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_PREVIEW_ONEPAGE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_PREVIEW_ONEPAGE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_PREVIEW_PREV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_PREVIEW_PREV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_PREVIEW_PRINT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_PREVIEW_PRINT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_PREVIEW_SETUP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_PREVIEW_SETUP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_PREVIEW_ZOOMIN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_PREVIEW_ZOOMIN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_PREVIEW_ZOOMOUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_PREVIEW_ZOOMOUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_VIEW_DETAILS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_VIEW_DETAILS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_VIEW_LARGEICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_VIEW_LARGEICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_VIEW_LIST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_VIEW_LIST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_VIEW_SMALLICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_VIEW_SMALLICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property IDB_VIEW_STRIPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IDB_VIEW_STRIPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  バージョン情報(&amp;A)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_APP_ABOUT() As String
            Get
                Return ResourceManager.GetString("IDM_APP_ABOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  終了(&amp;X) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_APP_EXIT() As String
            Get
                Return ResourceManager.GetString("IDM_APP_EXIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  編集(&amp;E) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_EDIT() As String
            Get
                Return ResourceManager.GetString("IDM_EDIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  削除(&amp;D)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_EDIT_CLEAR() As String
            Get
                Return ResourceManager.GetString("IDM_EDIT_CLEAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  コピー(&amp;C) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_EDIT_COPY() As String
            Get
                Return ResourceManager.GetString("IDM_EDIT_COPY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  切り取り(&amp;T) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_EDIT_CUT() As String
            Get
                Return ResourceManager.GetString("IDM_EDIT_CUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  検索(&amp;F)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_EDIT_FIND() As String
            Get
                Return ResourceManager.GetString("IDM_EDIT_FIND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  貼り付け(&amp;P) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_EDIT_PASTE() As String
            Get
                Return ResourceManager.GetString("IDM_EDIT_PASTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  次へ(&amp;N) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_EDIT_REPEAT() As String
            Get
                Return ResourceManager.GetString("IDM_EDIT_REPEAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  置換(&amp;N)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_EDIT_REPLACE() As String
            Get
                Return ResourceManager.GetString("IDM_EDIT_REPLACE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  すべて選択(&amp;A) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_EDIT_SELECT_ALL() As String
            Get
                Return ResourceManager.GetString("IDM_EDIT_SELECT_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  元に戻す(&amp;U) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_EDIT_UNDO() As String
            Get
                Return ResourceManager.GetString("IDM_EDIT_UNDO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイル(&amp;F) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_FILE() As String
            Get
                Return ResourceManager.GetString("IDM_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  新規作成(&amp;N) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_FILE_NEW() As String
            Get
                Return ResourceManager.GetString("IDM_FILE_NEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  開く(&amp;O)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_FILE_OPEN() As String
            Get
                Return ResourceManager.GetString("IDM_FILE_OPEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ページ設定(&amp;T)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_FILE_PAGE_SETUP() As String
            Get
                Return ResourceManager.GetString("IDM_FILE_PAGE_SETUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  印刷(&amp;P)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_FILE_PRINT() As String
            Get
                Return ResourceManager.GetString("IDM_FILE_PRINT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  印刷プレビュー(&amp;V)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_FILE_PRINT_PREVIEW() As String
            Get
                Return ResourceManager.GetString("IDM_FILE_PRINT_PREVIEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  印刷設定(&amp;T)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_FILE_PRINT_SETUP() As String
            Get
                Return ResourceManager.GetString("IDM_FILE_PRINT_SETUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  保存(&amp;S) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_FILE_SAVE() As String
            Get
                Return ResourceManager.GetString("IDM_FILE_SAVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  名前をつけて保存(&amp;A)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_FILE_SAVE_AS() As String
            Get
                Return ResourceManager.GetString("IDM_FILE_SAVE_AS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  送信(&amp;D)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_FILE_SEND_MAIL() As String
            Get
                Return ResourceManager.GetString("IDM_FILE_SEND_MAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ヘルプ(&amp;H) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_HELP() As String
            Get
                Return ResourceManager.GetString("IDM_HELP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  目次(&amp;C)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_HELP_CONTENTS() As String
            Get
                Return ResourceManager.GetString("IDM_HELP_CONTENTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ヘルプ検索(&amp;S)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_HELP_FINDER() As String
            Get
                Return ResourceManager.GetString("IDM_HELP_FINDER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  索引(&amp;I)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_HELP_INDEX() As String
            Get
                Return ResourceManager.GetString("IDM_HELP_INDEX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  編集(&amp;M) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_OLE_EDIT_PROPERTIES() As String
            Get
                Return ResourceManager.GetString("IDM_OLE_EDIT_PROPERTIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  挿入(&amp;I)... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_OLE_INSERT_NEW() As String
            Get
                Return ResourceManager.GetString("IDM_OLE_INSERT_NEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  表示(&amp;V) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_VIEW() As String
            Get
                Return ResourceManager.GetString("IDM_VIEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  詳細(&amp;D) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_VIEW_DETAILS() As String
            Get
                Return ResourceManager.GetString("IDM_VIEW_DETAILS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  大きいアイコン(&amp;G) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_VIEW_LARGEICON() As String
            Get
                Return ResourceManager.GetString("IDM_VIEW_LARGEICON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  一覧(&amp;L) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_VIEW_LIST() As String
            Get
                Return ResourceManager.GetString("IDM_VIEW_LIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  小さいアイコン(&amp;M) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_VIEW_SMALLICON() As String
            Get
                Return ResourceManager.GetString("IDM_VIEW_SMALLICON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ステータス バー(&amp;S) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_VIEW_STATUS_BAR() As String
            Get
                Return ResourceManager.GetString("IDM_VIEW_STATUS_BAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ツール バー(&amp;T) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDM_VIEW_TOOLBAR() As String
            Get
                Return ResourceManager.GetString("IDM_VIEW_TOOLBAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  テキストを入力してください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDP_AFXBARRES_TEXT_IS_REQUIRED() As String
            Get
                Return ResourceManager.GetString("IDP_AFXBARRES_TEXT_IS_REQUIRED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  中断 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_AFXBARRES_ABORT() As String
            Get
                Return ResourceManager.GetString("IDS_AFXBARRES_ABORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  キャンセル に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_AFXBARRES_CANCEL() As String
            Get
                Return ResourceManager.GetString("IDS_AFXBARRES_CANCEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Excel 8.0;HDR=YES に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_CONNECTION_EXTENDED_PROPERTIES() As String
            Get
                Return ResourceManager.GetString("IDS_CONNECTION_EXTENDED_PROPERTIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Microsoft.Jet.OLEDB.4.0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_CONNECTION_STRING_32() As String
            Get
                Return ResourceManager.GetString("IDS_CONNECTION_STRING_32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Microsoft.ACE.OLEDB.12.0 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_CONNECTION_STRING_64() As String
            Get
                Return ResourceManager.GetString("IDS_CONNECTION_STRING_64", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  編集 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_EDIT_MENU() As String
            Get
                Return ResourceManager.GetString("IDS_EDIT_MENU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  C:\Windows\Help\mui\0411\mmc.CHM に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_HELP_FILENAME() As String
            Get
                Return ResourceManager.GetString("IDS_HELP_FILENAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (不明)\n重大\n確認\n警告\n情報 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_MESSAGE_TITLES() As String
            Get
                Return ResourceManager.GetString("IDS_MESSAGE_TITLES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  select * from [Sheet1$] に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property IDS_SQL_SELECT() As String
            Get
                Return ResourceManager.GetString("IDS_SQL_SELECT", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
